### ISSUE TITLE
Getting Error in col2rgb: invalid color name '~' 

### ISSUE THREAD

**Issue by Ljupch0** [nsgrantham/ggdark#5] opened 2020-03-01 23:07 UTC
Hi,

When I get this error, I restart R and sometimes it works, sometimes it doesn't. What can be the source of this issue? Here's the traceback

  172: col2rgb
  171: invert_color
  170: invert_geom_defaults
  169: dark_mode
  168: dark_theme_gray
  167: renderPlot
  165: func
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$bars
    1: shiny::runApp

**Comment by nsgrantham** [comment] 2020-03-04 23:59
Hi @Ljupch0, can you share the code that causes this error?

**Comment by nsgrantham** [comment] 2020-08-08 19:03
Closing this because I do not have enough information to reproduce the error. Feel free to reopen if you're able to share a working example / more context.

**Closed as completed by nsgrantham** 2020-08-08 19:03 UTC
